In [15]:
import numpy as np

# Load the .npz file
data = np.load("shap.npz")

# List all keys (variable names stored inside)
print("Keys in .npz file:", data.files)

Keys in .npz file: ['sequences', 'contributions']


In [16]:
# Iterate through each key and print the first few lines
for key in data.files:
    print(f"Key: {key}")
    print(data[key][:5])  # Show first 5 rows (adjust as needed)
    print("-" * 40)  # Separator for clarity

Key: sequences
[[[1 0 1 ... 0 1 0]
  [0 1 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 1]]

 [[1 0 0 ... 1 0 0]
  [0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 1]
  [0 1 0 ... 0 1 0]]

 [[0 0 1 ... 0 0 0]
  [1 0 0 ... 0 0 1]
  [0 0 0 ... 1 0 0]
  [0 1 0 ... 0 1 0]]

 [[0 0 1 ... 0 1 0]
  [1 1 0 ... 1 0 1]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [1 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]
  [0 1 1 ... 0 1 1]]]
----------------------------------------
Key: contributions
[[[ 3.4451e-04 -5.7459e-04  4.9639e-04 ... -2.5201e-04 -1.3185e-04
   -4.1437e-04]
  [-7.7868e-04  5.7364e-04 -1.0214e-03 ... -1.2851e-04 -3.8552e-04
   -3.5882e-04]
  [-3.9554e-04 -5.0354e-04 -4.5609e-04 ... -1.2153e-04 -5.5027e-04
   -5.6934e-04]
  [-5.5313e-04 -1.3614e-04 -5.4264e-04 ... -3.5930e-04 -9.2328e-05
   -2.7537e-05]]

 [[-7.9989e-05  1.3626e-04  9.0241e-05 ...  5.6744e-04 -5.5838e-04
   -2.8539e-04]
  [ 1.6725e-04 -9.2030e-05 -1.7405e-04 ... -3.9434e-04 -5.8794e-04
   -6.7043e-04]
  [ 1.3924e-04 

In [17]:
# Save each key as a separate .npz file
for key in data.files:
    np.savez(f"{key}.npz", arr_0=data[key])  # Rename stored array to "arr_0"
    print(f"Saved {key}.npz with key renamed to 'arr_0'")

Saved sequences.npz with key renamed to 'arr_0'
Saved contributions.npz with key renamed to 'arr_0'


In [13]:
data = np.load("contributions.npz")

# List all keys (variable names stored inside)
print("Keys in .npz file:", data.files)

Keys in .npz file: ['contributions']


In [7]:
import h5py

# Open the HDF5 file
with h5py.File("chrombpnet_nobias.profile_scores.h5", "r") as h5f:
    print("Keys in HDF5 file:", list(h5f.keys()))

Keys in HDF5 file: ['projected_shap', 'raw', 'shap']


In [8]:
import h5py

# Open the HDF5 file
with h5py.File("../PS_EOd/auxiliary/interpret_subsample/chrombpnet_nobias.profile_scores.h5", "r") as h5f:
    print("Keys in HDF5 file:", list(h5f.keys()))

Keys in HDF5 file: ['projected_shap', 'raw', 'shap']


In [11]:
# Open the HDF5 file
with h5py.File("chrombpnet_nobias.profile_scores.h5", "r") as h5f:
    for key in h5f.keys():
        dataset = h5f[key]
        print(f"Key: {key}, Shape: {dataset.shape}, Type: {dataset.dtype}")
        print(dataset[:5])  # First 5 rows
        print("-" * 40)

AttributeError: 'Group' object has no attribute 'shape'